#!/usr/bin/env bash
# ==============================================================================
# ai-cluster-down.sh — Clean shutdown of the ai-cluster + pve3 power-off
#
# Drains workloads first (protects PVs and etcd), shuts down the Talos node
# (powers off the VM), THEN powers off the pve3 host itself via the Proxmox
# API — full power-off (energy-saving philosophy, no keep-alive flag).
#
# IMPORTANT: this script must run from a node that is NOT pve3 (e.g. pve0,
# which is online, or the Hermes host). The Proxmox API token must have
# PowerMgmt permissions on pve3.
#
# Run from examples/7-ai-cluster-single-node/ (configs generated by apply).
#
# Prerequisites:
#   - KUBECONFIG pointing at the ai-cluster (output/kube-config.yaml)
#   - kubectl installed
#   - talosctl installed (for the shutdown)
#   - Proxmox API access (PROXMOX_VE_ENDPOINT + PROXMOX_VE_API_TOKEN)
#
# Config:
#   AI_CLUSTER_TALOSCONFIG  talosconfig path        (default: output/talos-config.yaml)
#   AI_CLUSTER_NODE_NAME    k8s node name           (default: ai-cluster-cp-0)
#   AI_CLUSTER_NODE_IP      node IP for talosctl    (default: 192.168.10.203)
#   PROXMOX_VE_ENDPOINT     Proxmox API base URL    (required, e.g. https://pve0:8006)
#   PROXMOX_VE_API_TOKEN    API token user@realm!id=secret (required)
#   AI_CLUSTER_PVE3_NODE    Proxmox host to power off (default: pve3)
#
# Idempotent: safe to re-run at any point.
# ==============================================================================
set -euo pipefail

AI_CLUSTER_TALOSCONFIG="${AI_CLUSTER_TALOSCONFIG:-output/talos-config.yaml}"
AI_CLUSTER_NODE_NAME="${AI_CLUSTER_NODE_NAME:-ai-cluster-cp-0}"
AI_CLUSTER_NODE_IP="${AI_CLUSTER_NODE_IP:-192.168.10.203}"
AI_CLUSTER_KUBECONFIG="${AI_CLUSTER_KUBECONFIG:-output/kube-config.yaml}"
AI_CLUSTER_PVE3_NODE="${AI_CLUSTER_PVE3_NODE:-pve3}"

log()  { printf '[ai-cluster-down] %s\n' "$*"; }
fail() { printf '[ai-cluster-down] ERROR: %s\n' "$*" >&2; exit 1; }

# --- 1. Cordon the node (stop scheduling new workloads) ----------------------
cordon_node() {
  log "Cordoning node ${AI_CLUSTER_NODE_NAME}"
  if kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" get node "$AI_CLUSTER_NODE_NAME" -o name >/dev/null 2>&1; then
    kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" cordon "$AI_CLUSTER_NODE_NAME"
  else
    log "Node not found (already down?) — skipping cordon"
  fi
}

# --- 2. Drain workloads (safe eviction, protects PVs) ------------------------
drain_node() {
  log "Draining node ${AI_CLUSTER_NODE_NAME}"
  # --ignore-daemonsets: keep DaemonSets (nvidia-device-plugin) running
  # --delete-emptydir-data: allow eviction of pods using emptyDir
  if kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" get node "$AI_CLUSTER_NODE_NAME" -o name >/dev/null 2>&1; then
    kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" drain "$AI_CLUSTER_NODE_NAME" \
      --ignore-daemonsets \
      --delete-emptydir-data \
      --force
  else
    log "Node not found (already down?) — skipping drain"
  fi
}

# --- 3. Shut down the node via Talos (ordered halt, powers off the VM) -------
shutdown_node() {
  log "Shutting down ai-cluster via talosctl"
  talosctl --talosconfig "$AI_CLUSTER_TALOSCONFIG" \
    --nodes "$AI_CLUSTER_NODE_IP" \
    shutdown --wait
}

# --- 4. Power off the pve3 host via Proxmox API ------------------------------
# Runs from a reachable node (pve0 / Hermes host), NEVER from pve3 itself.
pve3_status() {
  curl -sS --fail \
    -H "Authorization: PVEAPI$(printf 'Token=%s' "${PROXMOX_VE_API_TOKEN}")" \
    "${PROXMOX_VE_ENDPOINT%/}/api2/json/nodes/${AI_CLUSTER_PVE3_NODE}/status" \
    | python3 -c "import json,sys; print(json.load(sys.stdin)['data']['status'])"
}

poweroff_pve3() {
  : "${PROXMOX_VE_ENDPOINT:?PROXMOX_VE_ENDPOINT required (Proxmox API base URL)}"
  : "${PROXMOX_VE_API_TOKEN:?PROXMOX_VE_API_TOKEN required (format user@realm!id=secret)}"

  log "Checking ${AI_CLUSTER_PVE3_NODE} status via Proxmox API"
  local status
  if status=$(pve3_status 2>/dev/null); then
    log "${AI_CLUSTER_PVE3_NODE} status: ${status}"
    if [ "$status" != "stopped" ]; then
      log "Powering off ${AI_CLUSTER_PVE3_NODE}"
      curl -sS --fail \
        -X POST \
        -H "Authorization: PVEAPI$(printf 'Token=%s' "${PROXMOX_VE_API_TOKEN}")" \
        --data-urlencode "command=shutdown" \
        "${PROXMOX_VE_ENDPOINT%/}/api2/json/nodes/${AI_CLUSTER_PVE3_NODE}/status"
      log "Power-off command sent to ${AI_CLUSTER_PVE3_NODE}"
    else
      log "${AI_CLUSTER_PVE3_NODE} already stopped — skipping"
    fi
  else
    log "Could not read ${AI_CLUSTER_PVE3_NODE} status (API unreachable?) — continuing without host power-off"
  fi
}

main() {
  cordon_node
  drain_node
  shutdown_node
  poweroff_pve3
  log "ai-cluster is DOWN (VM stopped, ${AI_CLUSTER_PVE3_NODE} powered off)"
}

main "$@"
