#!/usr/bin/env bash
# ==============================================================================
# ai-cluster-up.sh — Start the ai-cluster on pve3 (Wake-on-LAN + verify Ready)
#
# Philosophy: pve3 is powered off by default (energy saving). This script wakes
# it via WoL magic packet, waits for the VM to boot, then verifies the cluster
# nodes report Ready.
#
# Run from examples/7-ai-cluster-single-node/ (kubeconfig generated by apply).
#
# Prerequisites:
#   - KUBECONFIG pointing at the ai-cluster (output/kube-config.yaml)
#   - kubectl installed
#
# Config:
#   AI_CLUSTER_PVE3_MAC   MAC address of pve3          (default: 54:bf:64:6c:b8:53)
#   AI_CLUSTER_BROADCAST  LAN broadcast address        (default: 192.168.10.255)
#   AI_CLUSTER_WAIT_SEC   max seconds waiting for boot (default: 300)
#   AI_CLUSTER_NODE_IP    node IP                      (default: 192.168.10.203)
#   AI_CLUSTER_NODE_NAME  k8s node name for uncordon   (default: ai-cluster-cp-0)
#   AI_CLUSTER_PVE3_NODE  Proxmox host                 (default: pve3)
#   AI_CLUSTER_VMID       Proxmox VM ID                (required if VM must be started)
#   AI_CLUSTER_READY_TIMEOUT  ready wait timeout       (default: 300)
#   PROXMOX_VE_ENDPOINT   Proxmox API base URL         (required if VM must be started)
#   PROXMOX_VE_API_TOKEN  API token user@realm!id=secret (required if VM must be started)
#
# Idempotent: safe to re-run at any point.
# ==============================================================================
set -euo pipefail

AI_CLUSTER_PVE3_MAC="${AI_CLUSTER_PVE3_MAC:-54:bf:64:6c:b8:53}"
AI_CLUSTER_BROADCAST="${AI_CLUSTER_BROADCAST:-192.168.10.255}"
AI_CLUSTER_WAIT_SEC="${AI_CLUSTER_WAIT_SEC:-300}"
AI_CLUSTER_NODE_IP="${AI_CLUSTER_NODE_IP:-192.168.10.203}"
AI_CLUSTER_NODE_NAME="${AI_CLUSTER_NODE_NAME:-ai-cluster-cp-0}"
AI_CLUSTER_PVE3_NODE="${AI_CLUSTER_PVE3_NODE:-pve3}"
AI_CLUSTER_KUBECONFIG="${AI_CLUSTER_KUBECONFIG:-output/kube-config.yaml}"
AI_CLUSTER_READY_TIMEOUT="${AI_CLUSTER_READY_TIMEOUT:-300}"

log()  { printf '[ai-cluster-up] %s\n' "$*"; }
fail() { printf '[ai-cluster-up] ERROR: %s\n' "$*" >&2; exit 1; }
# --- 1. Send Wake-on-LAN magic packet (no Proxmox API needed) ---------------
send_wol() {
  log "Sending WoL to pve3 (MAC ${AI_CLUSTER_PVE3_MAC}, broadcast ${AI_CLUSTER_BROADCAST})"
  python3 - "$AI_CLUSTER_PVE3_MAC" "$AI_CLUSTER_BROADCAST" <<'PY'
import socket, sys

mac, broadcast = sys.argv[1], sys.argv[2]
mac_bytes = bytes.fromhex(mac.replace(":", ""))
magic = b"\xff" * 6 + mac_bytes * 16

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
s.sendto(magic, (broadcast, 9))
s.close()
PY
  log "WoL packet sent"
}

# --- 2. Ensure the VM is running (handle pve3 already up) -------------------
# If pve3 is already powered on (e.g. a previous down failed, or manual use),
# the WoL packet does nothing and the VM may not start (onboot applies only
# at host boot). Probe briefly; if the VM is not reachable, query the Proxmox
# API and start the VM explicitly.
ensure_vm_running() {
  # Short initial probe: if the VM answers quickly, pve3 booted and the VM is up.
  local deadline=$(( $(date +%s) + 30 ))
  while (( $(date +%s) < deadline )); do
    if nc -z -w 2 "$AI_CLUSTER_NODE_IP" 50000 2>/dev/null; then
      log "VM already reachable on ${AI_CLUSTER_NODE_IP}:50000"
      return 0
    fi
    sleep 5
  done

  : "${PROXMOX_VE_ENDPOINT:?PROXMOX_VE_ENDPOINT required to start the VM (Proxmox API base URL)}"
  : "${PROXMOX_VE_API_TOKEN:?PROXMOX_VE_API_TOKEN required (format user@realm!id=secret)}"
  : "${AI_CLUSTER_VMID:?AI_CLUSTER_VMID required (Proxmox VM ID of ai-cluster)}"

  log "VM not reachable after WoL — checking Proxmox VM ${AI_CLUSTER_VMID} on ${AI_CLUSTER_PVE3_NODE}"
  local vm_status
  if vm_status=$(curl -skS --fail \
      -H "Authorization: PVEAPI$(printf 'Token=%s' "${PROXMOX_VE_API_TOKEN}")" \
      "${PROXMOX_VE_ENDPOINT%/}/api2/json/nodes/${AI_CLUSTER_PVE3_NODE}/qemu/${AI_CLUSTER_VMID}/status/current" \
      2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin)['data']['status'])" 2>/dev/null); then
    log "VM ${AI_CLUSTER_VMID} status: ${vm_status}"
    if [ "$vm_status" = "stopped" ]; then
      log "Starting VM ${AI_CLUSTER_VMID}"
      curl -skS --fail \
        -X POST \
        -H "Authorization: PVEAPI$(printf 'Token=%s' "${PROXMOX_VE_API_TOKEN}")" \
        "${PROXMOX_VE_ENDPOINT%/}/api2/json/nodes/${AI_CLUSTER_PVE3_NODE}/qemu/${AI_CLUSTER_VMID}/status/start"
      log "Start command sent for VM ${AI_CLUSTER_VMID}"
    elif [ "$vm_status" = "running" ]; then
      log "VM ${AI_CLUSTER_VMID} already running (still booting?)"
    else
      log "VM ${AI_CLUSTER_VMID} status ${vm_status} — continuing to wait for boot"
    fi
  else
    log "Could not read VM ${AI_CLUSTER_VMID} status (API unreachable?) — continuing to wait for boot"
  fi
}

# --- 3. Wait for the VM to become reachable (Talos apid port 50000) ---------
wait_for_boot() {
  log "Waiting for ai-cluster to boot (up to ${AI_CLUSTER_WAIT_SEC}s)"
  local deadline=$(( $(date +%s) + AI_CLUSTER_WAIT_SEC ))
  while (( $(date +%s) < deadline )); do
    if nc -z -w 2 "$AI_CLUSTER_NODE_IP" 50000 2>/dev/null; then
      log "VM reachable on ${AI_CLUSTER_NODE_IP}:50000"
      return 0
    fi
    sleep 5
  done
  fail "Timed out waiting for ai-cluster to boot (${AI_CLUSTER_NODE_IP}:50000 not reachable)"
}

# --- 4. Verify nodes report Ready -------------------------------------------
wait_for_ready() {
  log "Verifying nodes Ready (up to ${AI_CLUSTER_READY_TIMEOUT}s)"
  if ! kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" wait --for=condition=Ready node --all --timeout="${AI_CLUSTER_READY_TIMEOUT}s" 2>/dev/null; then
    fail "Nodes not Ready after boot"
  fi
  log "Nodes Ready:"
  kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" get nodes
}

# --- 5. Un-cordon the node (down.sh cordons it; restore scheduling) ---------
uncordon_node() {
  log "Un-cordoning node ${AI_CLUSTER_NODE_NAME}"
  kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" uncordon "$AI_CLUSTER_NODE_NAME" || true
}

main() {
  send_wol
  ensure_vm_running
  wait_for_boot
  wait_for_ready
  uncordon_node
  log "ai-cluster is UP"
}

main "$@"
