#!/usr/bin/env bash
# ==============================================================================
# ai-cluster-up.sh — Start the ai-cluster on pve3 (Wake-on-LAN + verify Ready)
#
# Philosophy: pve3 is powered off by default (energy saving). This script wakes
# it via WoL magic packet, waits for the VM to boot, then verifies the cluster
# nodes report Ready.
#
# Run from examples/7-ai-cluster-single-node/ (kubeconfig generated by apply).
#
# Prerequisites:
#   - KUBECONFIG pointing at the ai-cluster (output/kube-config.yaml)
#   - kubectl installed
#
# Config:
#   AI_CLUSTER_PVE3_MAC   MAC address of pve3          (default: 54:bf:64:6c:b8:53)
#   AI_CLUSTER_BROADCAST  LAN broadcast address        (default: 192.168.10.255)
#   AI_CLUSTER_WAIT_SEC   max seconds waiting for boot (default: 300)
#
# Idempotent: safe to re-run at any point.
# ==============================================================================
set -euo pipefail

AI_CLUSTER_PVE3_MAC="${AI_CLUSTER_PVE3_MAC:-54:bf:64:6c:b8:53}"
AI_CLUSTER_BROADCAST="${AI_CLUSTER_BROADCAST:-192.168.10.255}"
AI_CLUSTER_WAIT_SEC="${AI_CLUSTER_WAIT_SEC:-300}"
AI_CLUSTER_NODE_IP="${AI_CLUSTER_NODE_IP:-192.168.10.203}"
AI_CLUSTER_KUBECONFIG="${AI_CLUSTER_KUBECONFIG:-output/kube-config.yaml}"

log()  { printf '[ai-cluster-up] %s\n' "$*"; }
fail() { printf '[ai-cluster-up] ERROR: %s\n' "$*" >&2; exit 1; }

# --- 1. Send Wake-on-LAN magic packet (no Proxmox API needed) ---------------
send_wol() {
  log "Sending WoL to pve3 (MAC ${AI_CLUSTER_PVE3_MAC}, broadcast ${AI_CLUSTER_BROADCAST})"
  python3 - "$AI_CLUSTER_PVE3_MAC" "$AI_CLUSTER_BROADCAST" <<'PY'
import socket, sys

mac, broadcast = sys.argv[1], sys.argv[2]
mac_bytes = bytes.fromhex(mac.replace(":", ""))
magic = b"\xff" * 6 + mac_bytes * 16

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
s.sendto(magic, (broadcast, 9))
s.close()
PY
  log "WoL packet sent"
}

# --- 2. Wait for the VM to become reachable (SSH port 22 on the node IP) ----
wait_for_boot() {
  log "Waiting for ai-cluster to boot (up to ${AI_CLUSTER_WAIT_SEC}s)"
  local deadline=$(( $(date +%s) + AI_CLUSTER_WAIT_SEC ))
  while (( $(date +%s) < deadline )); do
    if nc -z -w 2 "$AI_CLUSTER_NODE_IP" 22 2>/dev/null; then
      log "VM reachable on ${AI_CLUSTER_NODE_IP}:22"
      return 0
    fi
    sleep 5
  done
  fail "Timed out waiting for ai-cluster to boot (${AI_CLUSTER_NODE_IP}:22 not reachable)"
}

# --- 3. Verify nodes report Ready -------------------------------------------
wait_for_ready() {
  log "Verifying nodes Ready"
  if ! kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" wait --for=condition=Ready node --all --timeout=120s 2>/dev/null; then
    fail "Nodes not Ready after boot"
  fi
  log "Nodes Ready:"
  kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" get nodes
}

main() {
  send_wol
  wait_for_boot
  wait_for_ready
  log "ai-cluster is UP"
}

main "$@"
