#!/usr/bin/env bash
# ==============================================================================
# ai-cluster-down.sh — Clean shutdown of the ai-cluster (cordon + drain + halt)
#
# Drains workloads first (protects PVs and etcd), then shuts down the Talos
# node, which powers off the VM. pve3 then returns to its powered-off state
# (energy saving).
#
# Run from examples/7-ai-cluster-single-node/ (configs generated by apply).
#
# Prerequisites:
#   - KUBECONFIG pointing at the ai-cluster (output/kube-config.yaml)
#   - kubectl installed
#   - talosctl installed (for the shutdown)
#
# Config:
#   AI_CLUSTER_TALOSCONFIG  talosconfig path  (default: output/talos-config.yaml)
#   AI_CLUSTER_NODE_IP      node IP           (default: 192.168.10.203)
#
# Idempotent: safe to re-run at any point.
# ==============================================================================
set -euo pipefail

AI_CLUSTER_TALOSCONFIG="${AI_CLUSTER_TALOSCONFIG:-output/talos-config.yaml}"
AI_CLUSTER_NODE_IP="${AI_CLUSTER_NODE_IP:-192.168.10.203}"
AI_CLUSTER_KUBECONFIG="${AI_CLUSTER_KUBECONFIG:-output/kube-config.yaml}"

log()  { printf '[ai-cluster-down] %s\n' "$*"; }
fail() { printf '[ai-cluster-down] ERROR: %s\n' "$*" >&2; exit 1; }

# --- 1. Cordon the node (stop scheduling new workloads) ----------------------
cordon_node() {
  log "Cordoning node ${AI_CLUSTER_NODE_IP}"
  if kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" get node "$AI_CLUSTER_NODE_IP" -o name >/dev/null 2>&1; then
    kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" cordon "$AI_CLUSTER_NODE_IP"
  else
    log "Node not found (already down?) — skipping cordon"
  fi
}

# --- 2. Drain workloads (safe eviction, protects PVs) ------------------------
drain_node() {
  log "Draining node ${AI_CLUSTER_NODE_IP}"
  # --ignore-daemonsets: keep DaemonSets (nvidia-device-plugin) running
  # --delete-emptydir-data: allow eviction of pods using emptyDir
  if kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" get node "$AI_CLUSTER_NODE_IP" -o name >/dev/null 2>&1; then
    kubectl --kubeconfig "$AI_CLUSTER_KUBECONFIG" drain "$AI_CLUSTER_NODE_IP" \
      --ignore-daemonsets \
      --delete-emptydir-data \
      --force
  else
    log "Node not found (already down?) — skipping drain"
  fi
}

# --- 3. Shut down the node via Talos (ordered halt, powers off the VM) -------
shutdown_node() {
  log "Shutting down ai-cluster via talosctl"
  talosctl --talosconfig "$AI_CLUSTER_TALOSCONFIG" \
    --nodes "$AI_CLUSTER_NODE_IP" \
    shutdown --wait
}

main() {
  cordon_node
  drain_node
  shutdown_node
  log "ai-cluster is DOWN"
}

main "$@"
